# BankAccount Testing
################################################################################
#   This is the RSpec file to test the attributes defined in the original      #
#   BankAccount Class File. The attributes the orignial file is supposed to    #
#   include are listed below:                                                  #
################################################################################
# BankAccount should have a method that returns a user's account number, account
# number should be generated by a private method, account number should be random
# ==============================================================================
# BankAccount should have a method that returns the user's checking account balance
# ==============================================================================
# BankAccount should have a method that returns the user's saving account balance
# ==============================================================================
# BankAccount should allow a user to deposit money into either their checking
# or saving account
# ==============================================================================
# BankAccount should allow a user to withdraw money from one of their accounts,
# return an error if there are insufficient funds
# ==============================================================================
# BankAccount should allow the user to view the total amount of money they have
# at the bank
# ==============================================================================
# BankAccount should track how many accounts the bank currently has
# ==============================================================================
# BankAccount should have a private attribute called interest rate that is only
# displayed when the user calls the method account_information
# ==============================================================================
# BankAccount should have a method called account_information that displays the
# users account number, total money, checking account balance, saving account
# balance and interest rate
# ==============================================================================
# A user should not be able to set any attributes from the BankAccount class
# ==============================================================================


#The abilities the file

require_relative 'bank_account'

RSpec.describe BankAccount do
    before 'attribute tests' do
        @todds_account = BankAccount.new
        @todds_account.deposit_checking(12.53)
        @todds_account.transfer_to_savings(1.00)
        @account1 = BankAccount.new
        @account2 = BankAccount.new
        @account3 = BankAccount.new
        @account4 = BankAccount.new
    end #before

    describe 'attributes' do

        # ==============================================================================
        # BankAccount should have a method that returns a user's account number, account
        # number should be generated by a private method, account number should be random
        # ==============================================================================
        it "should return a random account number" do
            expect(@account1.account_number).not_to eql(@account2.account_number)
            expect(@account1.account_number).not_to eql(@account3.account_number)
            expect(@account1.account_number).not_to eql(@account4.account_number)
            expect(@account2.account_number).not_to eql(@account3.account_number)
            expect(@account2.account_number).not_to eql(@account4.account_number)
            expect(@account3.account_number).not_to eql(@account4.account_number)
        end

        it "should use a private method to generate the accont number" do
            expect { @account1.new_account_number }.to raise_exception(NoMethodError)
        end


        # ==============================================================================
        # BankAccount should have a method that returns the user's checking account balance
        # ==============================================================================
        it "should have a function that returns the users checking account balance" do
            expect(@todds_account.checking_balance_request).to eql(11.53)
        end
        # ==============================================================================
        # BankAccount should have a method that returns the user's saving account balance
        # ==============================================================================
        it "should have a method to return user's saveings account balance" do
            expect(@todds_account.savings_balance_request).to eql(1.00)
        end

        # ==============================================================================
        # BankAccount should allow a user to deposit money into either their checking
        # or saving account
        # ==============================================================================
        it "should allow user to deposit to either checking or savings" do
            account = BankAccount.new
            expect{account.deposit_savings(2.22)}.not_to raise_exception
            expect{account.deposit_checking(3.33)}.not_to raise_exception
            expect(account.savings_balance_request).to eq(2.22)
            expect(account.checking_balance_request).to eq(3.33)
        end

        # ==============================================================================
        # BankAccount should allow a user to withdraw money from one of their accounts,
        # return an error if there are insufficient funds
        # ==============================================================================
        it "should describe attribute here" do
            expect{@todds_account.withdraw_checking(5.00)}.not_to raise_exception
            expect(@todds_account.checking_balance_request).to eq(6.53)
            expect(@todds_account.withdraw_checking(20.00)).to eq("error, insufficient funds")
            expect(@todds_account.checking_balance_request).to eq(6.53)
        end

        # ==============================================================================
        # BankAccount should allow the user to view the total amount of money they have
        # at the bank
        # ==============================================================================
        it "should allow user to view the total amount of money they have at the bank" do
            tims_account = BankAccount.new
            tims_account.deposit_checking(12.53)
            tims_account.transfer_to_savings(1.00)
            expect(tims_account.balance_total).to eq(12.53)
        end

        # ==============================================================================
        # BankAccount should track how many accounts the bank currently has
        # ==============================================================================
        it "should track to how many bank accounts the bank currently has" do
            expect(BankAccount.accounts_tracker).to be > 4
        end

        # ==============================================================================
        # BankAccount should have a private attribute called interest rate that is only
        # displayed when the user calls the method account_information
        # ==============================================================================
        it "should have private attribute called interest_rate" do
            @account1 = BankAccount.new
            expect{ @account1.interest_rate }.to raise_exception(NoMethodError)
        end
#value () if capture {}
        it "should be displayed when the user calls method account_information" do # How to test this  <==========================|||||

        end

        # ==============================================================================
        # BankAccount should have a method called account_information that displays the
        # users account number, total money, checking account balance, saving account
        # balance and interest rate
        # ==============================================================================
        it "should describe attribute here" do  # How to test this  <=============================================================|||||
        end

        # ==============================================================================
        # A user should not be able to set any attributes from the BankAccount class
        # ==============================================================================
        it "should not allow the user to set attributes outside the BankAccount class" do
            @todds_account = BankAccount.new
            @todds_account.deposit_checking(12.53)
            @todds_account.transfer_to_savings(1.00)
            expect{@todds_account.balance_savings = 1000000}.to raise_exception(NoMethodError)
        end

    end
end
