# BankAccount Testing
################################################################################
#   This is the RSpec file to test the attributes defined in the original      #
#   BankAccount Class File. The attributes the orignial file is supposed to    #
#   include are listed below:                                                  #
################################################################################
# BankAccount should have a method that returns a user's account number, account
# number should be generated by a private method, account number should be random
# ==============================================================================
# BankAccount should have a method that returns the user's checking account balance
# ==============================================================================
# BankAccount should have a method that returns the user's saving account balance
# ==============================================================================
# BankAccount should allow a user to deposit money into either their checking
# or saving account
# ==============================================================================
# BankAccount should allow a user to withdraw money from one of their accounts,
# return an error if there are insufficient funds
# ==============================================================================
# BankAccount should allow the user to view the total amount of money they have
# at the bank
# ==============================================================================
# BankAccount should track how many accounts the bank currently has
# ==============================================================================
# BankAccount should have a private attribute called interest rate that is only
# displayed when the user calls the method account_information
# ==============================================================================
# BankAccount should have a method called account_information that displays the
# users account number, total money, checking account balance, saving account
# balance and interest rate
# ==============================================================================
# A user should not be able to set any attributes from the BankAccount class
# ==============================================================================


The abilities the file

require_relative 'bank_account'

RSpec.describe BankAccount do
    before do
    end #before
    describe 'attributes' do

        # ==============================================================================
        # BankAccount should have a method that returns a user's account number, account
        # number should be generated by a private method, account number should be random
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should have a method that returns the user's checking account balance
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should have a method that returns the user's saving account balance
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should allow a user to deposit money into either their checking
        # or saving account
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should allow a user to withdraw money from one of their accounts,
        # return an error if there are insufficient funds
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should allow the user to view the total amount of money they have
        # at the bank
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should track how many accounts the bank currently has
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should have a private attribute called interest rate that is only
        # displayed when the user calls the method account_information
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # BankAccount should have a method called account_information that displays the
        # users account number, total money, checking account balance, saving account
        # balance and interest rate
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # A user should not be able to set any attributes from the BankAccount class
        # ==============================================================================
        it "should describe attribute here" do
        end

        # ==============================================================================
        # Additional testing for the transfer method I have added.
        # ==============================================================================
        it "should describe attribute here" do
        end
    end
end
